### ISSUE TITLE
Динамик смартфона как бипер

### ISSUE THREAD

**Issue by Artemonim** [utkabobr/BeamKlipper#1]
## Что предлагается
Сделать так, чтобы из коробки можно было посылать тоновый сигнал через динамик смартфона.

## Почему
1. Звуковой сигнал при любой ошибке Клипера крайне полезен
2. На принтере без бипера появляется бипер без покупки бипера

**Comment by utkabobr** [comment]
Фича реализована.
Работает по `[include beam_beeper.cfg]`, появляется M300
