### ISSUE TITLE
Request for Klipperscreen

### ISSUE THREAD

**Issue by gleparc** [utkabobr/BeamKlipper#2]
Thank you for making this version of Klipper for Android!
I can confirm it is working on my Amazon Fire Tablet HD 8 (7th gen) and I also got the camera to work in Fluidd thanks to your instructions! Great job!

Would it be possible to have KlipperScreen running as well? Can you port KlipperScreen to Android? 
This would complete all the package in my opinion!

Thank you again!

**Comment by utkabobr** [comment]
Sorry, but KlipperScreen requires too much effort (X11, building GTK for Android, etc.). Also it's lacking animations and swipes that are available to implement on Android devices with good touchscreens and perfromance to handle this.
It's planned to make an alternative native Android app for this purpose.
