### ISSUE TITLE
how can i use happy hare

### ISSUE THREAD

**Issue by rootkgh** [utkabobr/BeamKlipper#4]
I install it
but config has only printer, not has mmu 

mmu config is not exist
if i upload mmu config file then is it works?

guide use happy hare bundle

**Comment by utkabobr** [comment]
It's installed in klippy/extras, so it will work with right configuration files, yes

**Comment by rootkgh** [comment]
> It's installed in klippy/extras, so it will work with right configuration files, yes

happy hare ver. is update
but yours is old version
so i set current ver's config, it is error by new variable

can you update happy hare ver.

**Comment by utkabobr** [comment]
Extras are built into APK, so it requires a new release. Will build it when I get home to my PC

**Comment by utkabobr** [comment]
Updated in 1.0.2

**Comment by rootkgh** [comment]
> Updated in 1.0.2

i install 1.0.2 
set config files, it is work

**Comment by utkabobr** [comment]
Closing as resolved
